production: &production
  bucket_name: <%= ENV.fetch('AWS_S3_BUCKET', 'canvas') %>
  access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID', 'somekey') %>
  secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY', 'some_secret_key') %>
  region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  force_path_style: <%= ENV.fetch('AWS_S3_FORCE_PATH_STYLE', false) %>
  endpoint: <%= ENV.fetch('AWS_ENDPOINT', 'https://s3.amazonaws.com') %>

test:
  <<: *production

development:
  <<: *production
