production: &production
  config:
    canvas:
      rich-content-service:
        app-host: <%= ENV.fetch('CANVAS_RCE_API_HOST', 'canvas-rce-api') %>

development:
  <<: *production

test:
  <<: *production
