production: &production
  encryption_key: <%= ENV["CANVAS_ENCRYPTION_KEY"] %>
  jwt_encryption_keys:
    - <%= ENV["CANVAS_JWT_ENCRYPTION_KEY"] %>
  lti_iss: <%= ENV["CANVAS_LTI_ISS"] %>

development:
  <<: *production

test:
  <<: *production
